version: '3'
services:
  phoenix:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: hello
      PGPORT: 5432
      PGHOST: db
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db
    command: mix ecto.create && mix ecto.migrate && mix phx.server
  db:
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: